name: CI

on:
  push:
    branches:
      - master
jobs:
  code_quality:
    name: Psalm example
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ffi
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction
      - name: Psalm
        run: ./vendor/bin/psalm --init
